[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.backends.legacy:build"

[project]
name = "secoem"
version = "0.1.0"
description = "Energy Community Optimization Model"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}

authors = [
    {name = ""}
]

dependencies = [
    "pyomo>=6.10",
    "PyYAML>=6.0",
]

[project.optional-dependencies]
dev = [
    "pytest",
]

[project.urls]
Homepage = "https://github.com/mmobec/secoem"
