BESS_datfile: "ec_BESS.dat"
wind_datfile: "ec_wind.dat"
market_datfile: "market.dat"
hydrogen_datfile: "ec_HYD.dat"

MODE: 'multiscen'

PROB: ["ec"]
probl: 'ec'
famscen: "FTC_2024_10"
include_h2: false
n_days: 3
project_root: "~/secoem" 

pathdem: "data/demand/"
pathdem_h2: "data/demand_h2/"

resfile: "results_log.res"
timefileFull: "time.txt"
numscenfile: "numscen.txt"

# Solver options
solver:
  name: "appsi_highs"
  MIPGap: 0.05
  Threads: 4
  DisplayInterval: 2
  Presolve: 0
  TimeLimit: 3600
  Seed: 2
  simplex_strategy: 1
